# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Health Care' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for Health Care
    pod 'AFNetworking', '~> 3.0'
    pod 'SDWebImage', '~>3.8'
    pod 'ImoDynamicTableView'
    pod 'SKTagView'
    pod 'MARKRangeSlider'
    pod 'CCBottomRefreshControl'
    pod 'BBBadgeBarButtonItem'
    pod 'HCSStarRatingView', '~> 1.5'
end
